/**
 * Decoder conformance against externally produced reference vectors.
 *
 * The vectors are (input PCM, MLow bitstream, output PCM) triples generated by
 * a separate native build of the same opus_mlow release, using the codec
 * configuration captured from a real WhatsApp call. The check is
 * `decode(packets) == output.s16`.
 *
 * Why it is worth running: generating both sides here would only prove this
 * library agrees with itself. A vector set produced independently catches a
 * divergent reading of the format — the class of bug that neither side finds
 * alone. It does NOT prove interoperation; no packet from a real call is
 * involved.
 *
 *   node scripts/check-golden.mjs [vectorsDir]
 */
import fs from "node:fs";
import path from "node:path";
import { DecoderCtl, createDecoder, loadLibopus, opusGlobalCreate } from "../dist/index.js";

const root = process.argv[2] ?? "G:/zapo-voip/findings/_peer/golden";
const SAMPLE_RATE = 16_000;
const CHANNELS = 1;
/**
 * 120 ms at 16 kHz — the codec's longest packet. The multiframe vectors pack two
 * native 60 ms frames, so a packet decodes to 1920 samples, not the 960 that the
 * "60ms" in their directory name suggests.
 */
const MAX_FRAME_SIZE = 1_920;

if (!fs.existsSync(root)) {
  console.error(`vectors not found: ${root}`);
  process.exit(2);
}

/** packets.bin is a u32 little-endian length followed by that many bytes, repeated. */
function readPackets(file) {
  const buf = fs.readFileSync(file);
  const packets = [];
  let off = 0;
  while (off + 4 <= buf.length) {
    const len = buf.readUInt32LE(off);
    off += 4;
    if (len === 0 || off + len > buf.length) break;
    packets.push(new Uint8Array(buf.subarray(off, off + len)));
    off += len;
  }
  return packets;
}

function readPcm(file) {
  const buf = fs.readFileSync(file);
  return new Int16Array(buf.buffer, buf.byteOffset, buf.byteLength / 2);
}

/** Signal-to-noise against the reference, in dB. Infinity means bit-exact. */
function snrDb(reference, actual) {
  const n = Math.min(reference.length, actual.length);
  let signal = 0;
  let noise = 0;
  let maxDelta = 0;
  for (let i = 0; i < n; i += 1) {
    const r = reference[i];
    const d = r - actual[i];
    signal += r * r;
    noise += d * d;
    if (Math.abs(d) > maxDelta) maxDelta = Math.abs(d);
  }
  return { snr: noise === 0 ? Infinity : 10 * Math.log10(signal / noise), maxDelta, compared: n };
}

const { version } = await loadLibopus();
opusGlobalCreate();
console.log(`codec   ${version}`);
console.log(`vectors ${root}\n`);

const dirs = fs
  .readdirSync(root, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

let failures = 0;
const rows = [];

for (const name of dirs) {
  const dir = path.join(root, name);
  const packetsFile = path.join(dir, "packets.bin");
  const outputFile = path.join(dir, "output.s16");
  if (!fs.existsSync(packetsFile) || !fs.existsSync(outputFile)) {
    rows.push({ name, status: "SKIP", detail: "missing packets.bin or output.s16" });
    continue;
  }

  const packets = readPackets(packetsFile);
  const expected = readPcm(outputFile);
  const decoder = await createDecoder({
    channels: CHANNELS,
    maxFrameSize: MAX_FRAME_SIZE,
    sampleRate: SAMPLE_RATE,
    useSmpl: true,
  });
  decoder.decoderCtl(DecoderCtl.SetUseSmpl, 1);

  try {
    const chunks = [];
    let decodedSamples = 0;
    let oneByte = 0;
    for (const packet of packets) {
      if (packet.byteLength === 1) oneByte += 1; // DTX comfort-noise frame
      const pcm = decoder.decode(packet, { maxFrameSize: MAX_FRAME_SIZE });
      chunks.push(pcm);
      decodedSamples += pcm.length;
    }

    const actual = new Int16Array(decodedSamples);
    let off = 0;
    for (const chunk of chunks) {
      actual.set(chunk, off);
      off += chunk.length;
    }

    const lengthMatches = actual.length === expected.length;
    const { snr, maxDelta, compared } = snrDb(expected, actual);
    const exact = lengthMatches && maxDelta === 0;
    const ok = lengthMatches && (exact || snr >= 80);
    if (!ok) failures += 1;

    rows.push({
      name,
      status: exact ? "BIT-EXACT" : ok ? "SNR-OK" : "FAIL",
      detail:
        `${packets.length} pkts` +
        (oneByte ? ` (${oneByte} DTX 1-byte)` : "") +
        ` · ${actual.length}/${expected.length} samples` +
        (exact ? "" : ` · SNR ${snr.toFixed(1)} dB, max Δ ${maxDelta}`) +
        (compared !== expected.length ? ` · compared ${compared}` : ""),
    });
  } catch (error) {
    failures += 1;
    rows.push({ name, status: "ERROR", detail: error.message });
  } finally {
    decoder.free();
  }
}

const width = Math.max(...rows.map((r) => r.name.length));
for (const row of rows) {
  console.log(`  ${row.name.padEnd(width)}  ${row.status.padEnd(9)}  ${row.detail}`);
}

console.log(
  `\n${rows.length - failures}/${rows.length} conform. ` +
    (failures === 0
      ? "This library and the reference build agree on the format."
      : "Divergence found — one of the two readings of the format is wrong."),
);
process.exit(failures === 0 ? 0 : 1);
