name: Benchmark

on:
  workflow_dispatch:

jobs:
  wasm:
    name: WASM throughput
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11.2.2

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 24

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 5.0.7

      - run: pnpm install --frozen-lockfile
      - run: pnpm benchmark
